import { createBeerFuriousGameDefinition } from "./games/beer-furious.js";
import { createBugRaceGameDefinition } from "./games/bug-race.js";
import { initializeModuleRuntime, registerGame } from "./core.js";
import { createDevilsPinGameDefinition } from "./games/devils-pin.js";
import { createDuelCombatGameDefinition } from "./games/duel-combat.js";
import { createKubokerGameDefinition } from "./games/kuboker.js";
import { registerModularLocalization } from "./localization.js";
import "./utility/texture-presets.js?v=20260915-prison-topdown-v100";
import "./actionplus/actionplus.js";
import "./actionplus/bloodmagic.js";
import "./actionplus/creature-attack.js";
import "./actionplus/damage-adjustments.js";
import "./actionplus/critical-specialization.js";
import "./actionplus/enhancement.js";
import "./actionplus/regeneration.js";
import "./actionplus/light-blindness.js";
import "./actionplus/degree-of-success.js";
import "./actionplus/affliction.js";
import "./actionplus/actor-extras.js";
import "./utility/journals/index.js";
import "./utility/read.js";
import "./utility/wall-textures.js?v=20260915-prison-topdown-v100";
import "./utility/floor-textures.js?v=20260915-prison-topdown-v100";
import "./utility/obstructing-forest.js?v=20260907-obstructing-forest-v1";
import "./utility/horror-mode.js";
import "./utility/scene-assets.js?v=20260915-prison-topdown-v100";
import "./utility/mirror-reflections.js?v=20260915-prison-topdown-v100";
import "./utility/scene-decorator.js?v=20260915-prison-topdown-v100";
import "./utility/scene-eye.js";
import "./utility/thumb.js";
import "./utility/spell-at-will.js";
import "./utility/ritual-checks.js";
import "./actionplus/spell-set.js";
import "./actionplus/coven.js";
import "./actionplus/alchemy.js";
import "./actionplus/appearances.js";
import "./actionplus/shoulder-to-shoulder.js";
import "./actionplus/troop-damage.js";
import "./actionplus/debilitating-strike.js";
import "./actionplus/speeds.js";
import "./actionplus/mounted-combat.js";
import "./actionplus/familiar-owner.js";
import "./utility/creature-corrections.js";
import "./utility/temp-hp.js";
import "./utility/damage-save.js";
import "./utility/hunt-prey-target.js";
import "./utility/light-switch.js?v=20260915-prison-topdown-v100";
import "./campaigns/bastardhall.js?v=20260915-prison-topdown-v100";
import "./utility/bastion-gallery.js?v=20260915-prison-topdown-v100";

registerModularLocalization();
registerGame(createBeerFuriousGameDefinition());
registerGame(createBugRaceGameDefinition());
registerGame(createDevilsPinGameDefinition());
registerGame(createDuelCombatGameDefinition());
registerGame(createKubokerGameDefinition());
initializeModuleRuntime();
